In [3]:
import pandas as pd 
import numpy as np

In [2]:
print(pd.__version__)

2.2.3


In [5]:
s = pd.Series([1,2,5,np.nan,6,8])
s

0    1.0
1    2.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
dates = pd.date_range('20250102', periods=6)
dates

DatetimeIndex(['2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05',
               '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')

In [8]:
df = pd.DataFrame(np.random.randn(6,4), index=dates,columns= ['A','B','C','D']) 
df

A         B         C         D
2025-01-02  0.061955 -0.530917 -0.225295 -0.830779
2025-01-03  1.320650  0.446949  0.588841 -0.433302
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949
2025-01-05  0.863358  1.097348 -0.661238  1.511925
2025-01-06  0.280590  0.464021 -1.081169  0.249518
2025-01-07 -0.750100 -0.701807  1.720254  0.290831

In [9]:
df.head(10)

A         B         C         D
2025-01-02  0.061955 -0.530917 -0.225295 -0.830779
2025-01-03  1.320650  0.446949  0.588841 -0.433302
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949
2025-01-05  0.863358  1.097348 -0.661238  1.511925
2025-01-06  0.280590  0.464021 -1.081169  0.249518
2025-01-07 -0.750100 -0.701807  1.720254  0.290831

In [10]:
df.tail(3)

A         B         C         D
2025-01-05  0.863358  1.097348 -0.661238  1.511925
2025-01-06  0.280590  0.464021 -1.081169  0.249518
2025-01-07 -0.750100 -0.701807  1.720254  0.290831

In [13]:
print("index:" , df.index)
print("columns:" , df.columns) 
print("values:" , df.values)

index: DatetimeIndex(['2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05',
               '2025-01-06', '2025-01-07'],
              dtype='datetime64[ns]', freq='D')
columns: Index(['A', 'B', 'C', 'D'], dtype='object')
values: [[ 0.06195507 -0.53091745 -0.22529514 -0.83077877]
 [ 1.3206502   0.44694896  0.58884105 -0.43330219]
 [-0.1060948  -1.05945582  0.3436376  -1.17394871]
 [ 0.86335812  1.09734836 -0.6612385   1.51192535]
 [ 0.28058951  0.4640205  -1.08116946  0.24951806]
 [-0.75010008 -0.70180747  1.72025396  0.29083084]]


In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2025-01-02 to 2025-01-07
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [16]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.278393 -0.047310  0.114172 -0.064293
std    0.732252  0.836980  1.000280  0.965822
min   -0.750100 -1.059456 -1.081169 -1.173949
25%   -0.064082 -0.659085 -0.552253 -0.731410
50%    0.171272 -0.041984  0.059171 -0.091892
75%    0.717666  0.459753  0.527540  0.280503
max    1.320650  1.097348  1.720254  1.511925

In [17]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2025-01-02 -0.830779 -0.225295 -0.530917  0.061955
2025-01-03 -0.433302  0.588841  0.446949  1.320650
2025-01-04 -1.173949  0.343638 -1.059456 -0.106095
2025-01-05  1.511925 -0.661238  1.097348  0.863358
2025-01-06  0.249518 -1.081169  0.464021  0.280590
2025-01-07  0.290831  1.720254 -0.701807 -0.750100

In [18]:
df.sort_values(by="B")

A         B         C         D
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949
2025-01-07 -0.750100 -0.701807  1.720254  0.290831
2025-01-02  0.061955 -0.530917 -0.225295 -0.830779
2025-01-03  1.320650  0.446949  0.588841 -0.433302
2025-01-06  0.280590  0.464021 -1.081169  0.249518
2025-01-05  0.863358  1.097348 -0.661238  1.511925

In [19]:
df['A']

2025-01-02    0.061955
2025-01-03    1.320650
2025-01-04   -0.106095
2025-01-05    0.863358
2025-01-06    0.280590
2025-01-07   -0.750100
Freq: D, Name: A, dtype: float64

In [21]:
df.loc['2025-01-02']

A    0.061955
B   -0.530917
C   -0.225295
D   -0.830779
Name: 2025-01-02 00:00:00, dtype: float64

In [22]:
df.iloc[0]

A    0.061955
B   -0.530917
C   -0.225295
D   -0.830779
Name: 2025-01-02 00:00:00, dtype: float64

In [23]:
df[:3]

A         B         C         D
2025-01-02  0.061955 -0.530917 -0.225295 -0.830779
2025-01-03  1.320650  0.446949  0.588841 -0.433302
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949

In [24]:
df['2025-01-02': '2025-01-05']

A         B         C         D
2025-01-02  0.061955 -0.530917 -0.225295 -0.830779
2025-01-03  1.320650  0.446949  0.588841 -0.433302
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949
2025-01-05  0.863358  1.097348 -0.661238  1.511925

In [27]:
df.loc['2025-01-02':'2025-01-04', ["A","B"]]

A         B
2025-01-02  0.061955 -0.530917
2025-01-03  1.320650  0.446949
2025-01-04 -0.106095 -1.059456

In [29]:
df.loc['2025-01-02', "B"]

-0.5309174529190444

In [31]:
df.iloc[3:6, 0:2]

A         B
2025-01-05  0.863358  1.097348
2025-01-06  0.280590  0.464021
2025-01-07 -0.750100 -0.701807

In [32]:
df.iloc[[1,2,3],[0,3]]

A         D
2025-01-03  1.320650 -0.433302
2025-01-04 -0.106095 -1.173949
2025-01-05  0.863358  1.511925

In [33]:
df.iloc[1:3,:]

A         B         C         D
2025-01-03  1.320650  0.446949  0.588841 -0.433302
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949

In [34]:
df[df>0]

A         B         C         D
2025-01-02  0.061955       NaN       NaN       NaN
2025-01-03  1.320650  0.446949  0.588841       NaN
2025-01-04       NaN       NaN  0.343638       NaN
2025-01-05  0.863358  1.097348       NaN  1.511925
2025-01-06  0.280590  0.464021       NaN  0.249518
2025-01-07       NaN       NaN  1.720254  0.290831

In [35]:
df[df['A']> 0 ]

A         B         C         D
2025-01-02  0.061955 -0.530917 -0.225295 -0.830779
2025-01-03  1.320650  0.446949  0.588841 -0.433302
2025-01-05  0.863358  1.097348 -0.661238  1.511925
2025-01-06  0.280590  0.464021 -1.081169  0.249518

In [38]:
df['E'] = ['one','one','two','three','two','four']
df

A         B         C         D      E
2025-01-02  0.061955 -0.530917 -0.225295 -0.830779    one
2025-01-03  1.320650  0.446949  0.588841 -0.433302    one
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949    two
2025-01-05  0.863358  1.097348 -0.661238  1.511925  three
2025-01-06  0.280590  0.464021 -1.081169  0.249518    two
2025-01-07 -0.750100 -0.701807  1.720254  0.290831   four

In [39]:
df['E'].isin(['two','four']) ## masking 

2025-01-02    False
2025-01-03    False
2025-01-04     True
2025-01-05    False
2025-01-06     True
2025-01-07     True
Freq: D, Name: E, dtype: bool

In [41]:
df[df['E'].isin(['two','four'])] ### chain  indexing 

A         B         C         D     E
2025-01-04 -0.106095 -1.059456  0.343638 -1.173949   two
2025-01-06  0.280590  0.464021 -1.081169  0.249518   two
2025-01-07 -0.750100 -0.701807  1.720254  0.290831  four