In [1]:
import numpy as np

# 예시 데이터
data = np.array([23, 12, 45, 67, 34, 89, 22, 65, 44, 55])

# 평균, 표준편차, 최대값, 최소값 계산
mean_val = np.mean(data)
std_val = np.std(data)
max_val = np.max(data)
min_val = np.min(data)

print("평균:", mean_val)
print("표준편차:", std_val)
print("최대값:", max_val)
print("최소값:", min_val)


평균: 45.6
표준편차: 22.67245024253003
최대값: 89
최소값: 12


In [2]:
import numpy as np
# 1D 배열
arr = np.array([1, 2, 3, 4, 5, 6])

# 2D 배열로 reshape
reshaped_arr = arr.reshape(2, 3)  # 2행 3열로 변환
print("2D 배열:\n", reshaped_arr)

# 배열의 전치 (행과 열 바꾸기)
transposed_arr = reshaped_arr.T
print("전치된 배열:\n", transposed_arr)


2D 배열:
 [[1 2 3]
 [4 5 6]]
전치된 배열:
 [[1 4]
 [2 5]
 [3 6]]


In [3]:
# 예시 데이터
import numpy as np

arr = np.array([12, 56, 43, 87, 24, 67, 99])

# 50보다 큰 값만 선택
filtered_arr = arr[arr > 50]
print("50보다 큰 값들:", filtered_arr)


50보다 큰 값들: [56 87 67 99]


In [4]:
import numpy as np 

# 행렬 A, B 정의
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 행렬 곱셈
result = np.dot(A, B)
print("행렬 곱셈 결과:\n", result)


행렬 곱셈 결과:
 [[19 22]
 [43 50]]


In [5]:
import numpy as np 

# 두 벡터
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

# 코사인 유사도 계산 (내적 / (벡터1의 크기 * 벡터2의 크기))
cosine_similarity = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
print("코사인 유사도:", cosine_similarity)


코사인 유사도: 0.9746318461970762
