In [ ]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
####### !pip install scikit-learn

# 문서 예시
documents = [
    "I love programming in Python",
    "Python programming is fun",
    "I love coding in Python",
    "I am learning machine learning"
]

# TF-IDF 벡터화
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(documents)

# 변환된 TF-IDF 행렬을 Numpy 배열로 변환
tfidf_matrix = X.toarray()

# 결과 출력
print("TF-IDF 행렬:")
print(tfidf_matrix)



TF-IDF 행렬:
[[0.         0.         0.         0.52303503 0.         0.
  0.52303503 0.         0.52303503 0.42344193]
 [0.         0.         0.57457953 0.         0.57457953 0.
  0.         0.         0.4530051  0.36674667]
 [0.         0.61422608 0.         0.4842629  0.         0.
  0.4842629  0.         0.         0.39205255]
 [0.40824829 0.         0.         0.         0.         0.81649658
  0.         0.40824829 0.         0.        ]]


In [1]:
import numpy as np


In [2]:
import numpy as np

# 1D 배열
arr1 = np.array([1, 2, 3, 4])
print("1D 배열:", arr1)

# 2D 배열
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
print("2D 배열:\n", arr2)


1D 배열: [1 2 3 4]
2D 배열:
 [[1 2]
 [3 4]
 [5 6]]


In [4]:
# 배열의 첫 번째 요소
print("첫 번째 요소:", arr1[0])

# 2D 배열에서 2번째 행, 2번째 열 값
print("2D 배열에서 특정 값:", arr2[1, 1])

# 슬라이싱
print("배열의 첫 3개 요소:", arr1[:3])


첫 번째 요소: 1
2D 배열에서 특정 값: 4
배열의 첫 3개 요소: [1 2 3]


In [5]:
arr3 = np.array([1, 2, 3, 4])

# 합 구하기
print("합:", np.sum(arr3))

# 평균 구하기
print("평균:", np.mean(arr3))

# 배열 간 연산
arr4 = np.array([5, 6, 7, 8])
print("배열 간 더하기:", arr3 + arr4)


합: 10
평균: 2.5
배열 간 더하기: [ 6  8 10 12]


In [6]:
import numpy as np

# Numpy 배열 생성
arr = np.array([1, 2, 3, 4, 5])
print("Numpy 배열:", arr)

# Python 리스트
lst = [1, 2, 3, 4, 5]
print("Python 리스트:", lst)

# Numpy 배열로 벡터화 연산 가능
arr_sum = arr + 10
print("배열에 10 더하기:", arr_sum)


Numpy 배열: [1 2 3 4 5]
Python 리스트: [1, 2, 3, 4, 5]
배열에 10 더하기: [11 12 13 14 15]


In [7]:
# np.arange() 사용
arr1 = np.arange(0, 10, 2)
print("np.arange(0, 10, 2):", arr1)

# np.linspace() 사용
arr2 = np.linspace(0, 1, 5)
print("np.linspace(0, 1, 5):", arr2)

# np.zeros() 사용
arr3 = np.zeros((2, 3))
print("np.zeros((2, 3)):\n", arr3)

# np.ones() 사용
arr4 = np.ones((3, 2))
print("np.ones((3, 2)):\n", arr4)

# np.eye() 사용
arr5 = np.eye(3)
print("np.eye(3):\n", arr5)


np.arange(0, 10, 2): [0 2 4 6 8]
np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]
np.ones((3, 2)):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("배열의 형태:", arr.shape)  # (2, 3)
print("배열의 크기:", arr.size)   # 6
print("배열의 차원:", arr.ndim)   # 2
print("배열의 데이터 타입:", arr.dtype)  # int64


배열의 형태: (2, 3)
배열의 크기: 6
배열의 차원: 2
배열의 데이터 타입: int64


In [9]:
# reshape() 사용
reshaped = arr.reshape(3, 2)
print("reshape(3, 2):\n", reshaped)

# resize() 사용
arr.resize(3, 2)
print("resize(3, 2):\n", arr)


reshape(3, 2):
 [[1 2]
 [3 4]
 [5 6]]
resize(3, 2):
 [[1 2]
 [3 4]
 [5 6]]


In [10]:
arr1d = np.array([10, 20, 30, 40, 50])

# 첫 번째 요소
print("첫 번째 요소:", arr1d[0])

# 마지막 요소
print("마지막 요소:", arr1d[-1])


첫 번째 요소: 10
마지막 요소: 50


In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 첫 번째 행
print("첫 번째 행:", arr2d[0])

# 두 번째 열
print("두 번째 열:", arr2d[:, 1])

# 2x2 부분 배열 (슬라이싱)
print("슬라이싱된 배열:\n", arr2d[0:2, 1:3])


첫 번째 행: [1 2 3]
두 번째 열: [2 5 8]
슬라이싱된 배열:
 [[2 3]
 [5 6]]


In [12]:
import numpy as np

# 1D 배열
arr1d = np.array([1, 2, 3, 4, 5])
print("1D 배열의 형태:", arr1d.shape)  # (5,)

# 2D 배열
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D 배열의 형태:", arr2d.shape)  # (3, 3)

# 3D 배열
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D 배열의 형태:", arr3d.shape)  # (2, 2, 2)


1D 배열의 형태: (5,)
2D 배열의 형태: (3, 3)
3D 배열의 형태: (2, 2, 2)


In [13]:
print("1D 배열의 크기:", arr1d.size)  # 5
print("2D 배열의 크기:", arr2d.size)  # 9
print("3D 배열의 크기:", arr3d.size)  # 8

print("1D 배열의 차원 수:", arr1d.ndim)  # 1
print("2D 배열의 차원 수:", arr2d.ndim)  # 2
print("3D 배열의 차원 수:", arr3d.ndim)  # 3

arr_int = np.array([1, 2, 3, 4], dtype=int)
print("배열의 데이터 타입:", arr_int.dtype)  # int64

arr_float = np.array([1.1, 2.2, 3.3], dtype=float)
print("배열의 데이터 타입:", arr_float.dtype)  # float64


1D 배열의 크기: 5
2D 배열의 크기: 9
3D 배열의 크기: 8
1D 배열의 차원 수: 1
2D 배열의 차원 수: 2
3D 배열의 차원 수: 3
배열의 데이터 타입: int64
배열의 데이터 타입: float64


In [14]:
import numpy as np

# 두 배열 생성
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# 배열 간의 산술 연산
print("덧셈:", arr1 + arr2)  # [ 6  8 10 12]
print("뺄셈:", arr1 - arr2)  # [-4 -4 -4 -4]
print("곱셈:", arr1 * arr2)  # [ 5 12 21 32]
print("나눗셈:", arr1 / arr2)  # [0.2 0.33333333 0.42857143 0.5]
print("거듭제곱:", arr1 ** 2)  # [ 1  4  9 16]


덧셈: [ 6  8 10 12]
뺄셈: [-4 -4 -4 -4]
곱셈: [ 5 12 21 32]
나눗셈: [0.2        0.33333333 0.42857143 0.5       ]
거듭제곱: [ 1  4  9 16]


In [15]:
arr = np.array([1, 2, 3, 4, 5])

# 합, 평균, 최대값, 최소값 구하기
print("합:", np.sum(arr))  # 15
print("평균:", np.mean(arr))  # 3.0
print("최대값:", np.max(arr))  # 5
print("최소값:", np.min(arr))  # 1


합: 15
평균: 3.0
최대값: 5
최소값: 1


In [16]:
arr = np.array([1, 2, 3, 4, 5])

# 표준편차와 분산 구하기
print("표준편차:", np.std(arr))  # 1.4142135623730951
print("분산:", np.var(arr))  # 2.0


표준편차: 1.4142135623730951
분산: 2.0


## 수학적 연산 함수
- np.add(), np.subtract(), np.multiply(), np.divide() 등: 기본적인 산술 연산 함수들입니다. 배열 간 연산을 수행할 때 사용됩니다.
- np.power(): 배열의 각 요소에 거듭제곱을 적용합니다.
- np.sqrt(): 배열의 각 요소에 대해 제곱근을 구합니다.
- np.exp(): 배열의 각 요소에 대해 지수 함수 계산을 수행합니다.
- np.log(): 배열의 각 요소에 대해 자연로그를 계산합니다.
- 예시

In [17]:
import numpy as np

# 배열 생성
arr = np.array([1, 4, 9, 16, 25])

# 제곱근 계산
sqrt_arr = np.sqrt(arr)
print("제곱근:", sqrt_arr)  # [1. 2. 3. 4. 5.]

# 자연로그 계산
log_arr = np.log(arr)
print("자연로그:", log_arr)

# 거듭제곱 계산
power_arr = np.power(arr, 2)
print("거듭제곱:", power_arr)


제곱근: [1. 2. 3. 4. 5.]
자연로그: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
거듭제곱: [  1  16  81 256 625]


## 주요 Aggregation 함수
- 합계, 평균, 최소값, 최대값
- np.sum(): 배열의 모든 값을 더한 합계를 계산합니다.
- np.mean(): 배열의 평균값을 계산합니다.
- np.min(), np.max(): 배열의 최소값과 최대값을 계산합니다.
## 통계적 함수
- np.std(): 배열의 표준편차를 계산합니다.
- np.var(): 배열의 분산을 계산합니다.
- np.median(): 배열의 중앙값을 계산합니다.
- np.percentile(): 배열에서 특정 백분위수 값을 계산합니다.
## 다차원 배열에 대한 집계
- np.sum(axis=0), np.mean(axis=1): 특정 축(axis)에 대해 집계를 수행할 수 있습니다.
- np.cumsum(): 배열의 누적 합을 계산합니다.
- np.cumprod(): 배열의 누적 곱을 계산합니다.


In [18]:
arr = np.array([1, 2, 3, 4, 5])

# 배열의 합, 평균, 최소값, 최대값
print("합:", np.sum(arr))  # 15
print("평균:", np.mean(arr))  # 3.0
print("최소값:", np.min(arr))  # 1
print("최대값:", np.max(arr))  # 5

# 표준편차와 분산
print("표준편차:", np.std(arr))  # 1.4142135623730951
print("분산:", np.var(arr))  # 2.0

# 중앙값
print("중앙값:", np.median(arr))  # 3.0

# 백분위수 (25th percentile)
print("25th 백분위수:", np.percentile(arr, 25))  # 2.0

# 누적 합
cumsum_arr = np.cumsum(arr)
print("누적 합:", cumsum_arr)  # [ 1  3  6 10 15]

# 누적 곱
cumprod_arr = np.cumprod(arr)
print("누적 곱:", cumprod_arr)  # [  1   2   6  24 120]


합: 15
평균: 3.0
최소값: 1
최대값: 5
표준편차: 1.4142135623730951
분산: 2.0
중앙값: 3.0
25th 백분위수: 2.0
누적 합: [ 1  3  6 10 15]
누적 곱: [  1   2   6  24 120]
