In [1]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3.14, 4, 2, 3])
a, b

In [ ]:
c = np.array([1, 2, 3, 4], dtype=float)
c

In [ ]:
data = [1, 2, 3, 4, 5]
data2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr1 = np.array(data)
print(arr1, type(arr1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
arr1.shape

(5,)

In [ ]:
arr2 = np.array(data2, dtype=float)
arr2, type(arr2)

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 numpy.ndarray)

In [ ]:
print(arr2.shape)

(3, 3)


In [ ]:
print(" arr2의 ndim:", arr2.ndim)
print(" arr2의 shape:", arr2.shape)
print(" arr2의 size:", arr2.size)
print(" arr2의 dype:", arr2.dtype)
print(" arr2의 itemsize:", arr2.itemsize)
print(" arr2의 nbytes:", arr2.nbytes)

 arr2의 ndim: 2
 arr2의 shape: (3, 3)
 arr2의 size: 9
 arr2의 dype: float64
 arr2의 itemsize: 8
 arr2의 nbytes: 72


In [ ]:
#### 초기화
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.zeros(10, dtype=int)
a

In [17]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.ones((3, 5), dtype=float)
b

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
c = np.full((3, 5), 3.14)
c

In [ ]:
x2 = np.random.random(size=(10, 5))
x2

In [ ]:
arr_1 = np.random.randint(1, 10, size=10**8)

In [ ]:
v1 = np.array((1, 2, 3))
v2 = np.array((4, 5, 6))
print(v1 + v2)
print(v1 * v2)

[5 7 9]
[ 4 10 18]


In [ ]:
t1 = (1, 2, 3)
t2 = (4, 5, 6)
print(t1 + t2)

L = []
for x, y in zip(t1, t2):
    a = x + y
    L.append(a)
L

(1, 2, 3, 4, 5, 6)


[5, 7, 9]

In [ ]:
###Broad Casting

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1.shape

(2, 3)

In [ ]:
arr2 = np.array([7, 8, 9])
arr2.shape

(3,)

In [ ]:
arr1 + arr2  ### [1,2,3] + [7,8,9] // [4,5,6] + [7,8,9]

array([[ 8, 10, 12],
       [11, 13, 15]])

In [ ]:
arr1 * arr2

array([[ 7, 16, 27],
       [28, 40, 54]])

In [ ]:
arr1 = np.array([1, 2, 3])
print(arr1 / 1)
print(1 / arr1)

[1. 2. 3.]
[1.         0.5        0.33333333]


In [ ]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2[1, 2]

7

In [46]:
arr2[2]

array([ 9, 10, 11, 12])

In [ ]:
arr2[:, 2]

array([ 3,  7, 11])

In [ ]:
mask = np.array([0, 0, 1, 1, 1, 0, 0])
mask

array([0, 0, 1, 1, 1, 0, 0])

In [ ]:
data = np.random.randn(7, 4)
data

array([[ 1.30818189, -0.88204841,  1.07695746,  0.25293496],
       [ 0.57635314,  0.74684045, -0.19111946, -0.7459267 ],
       [ 0.04952609,  0.23660924,  0.06011918, -1.04319668],
       [ 0.24474872,  0.56339259,  2.49730201,  2.233948  ],
       [ 0.19677296,  1.54839807, -0.99650156, -0.08367778],
       [-0.93738583,  1.27610445, -0.73809116, -0.26314202],
       [ 0.77914736,  0.52681879, -0.07465362, -0.19856316]])

In [ ]:
masked_data = mask == 1
masked_data

array([False, False,  True,  True,  True, False, False])

In [ ]:
data[masked_data, :]

array([[ 0.04952609,  0.23660924,  0.06011918, -1.04319668],
       [ 0.24474872,  0.56339259,  2.49730201,  2.233948  ],
       [ 0.19677296,  1.54839807, -0.99650156, -0.08367778]])

In [ ]:
data[mask == 0, :]

array([[ 1.30818189, -0.88204841,  1.07695746,  0.25293496],
       [ 0.57635314,  0.74684045, -0.19111946, -0.7459267 ],
       [-0.93738583,  1.27610445, -0.73809116, -0.26314202],
       [ 0.77914736,  0.52681879, -0.07465362, -0.19856316]])

In [ ]:
print(data[:, 0])
print(data[:, 0] > 0)

[ 1.30818189  0.57635314  0.04952609  0.24474872  0.19677296 -0.93738583
  0.77914736]
[ True  True  True  True  True False  True]


In [ ]:
data[data[:, 0] > 0, :]

array([[ 1.30818189, -0.88204841,  1.07695746,  0.25293496],
       [ 0.57635314,  0.74684045, -0.19111946, -0.7459267 ],
       [ 0.04952609,  0.23660924,  0.06011918, -1.04319668],
       [ 0.24474872,  0.56339259,  2.49730201,  2.233948  ],
       [ 0.19677296,  1.54839807, -0.99650156, -0.08367778],
       [ 0.77914736,  0.52681879, -0.07465362, -0.19856316]])

In [ ]:
data[data[:, 0] > 0, :] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.93738583,  1.27610445, -0.73809116, -0.26314202],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [ ]:
x1 = np.arange(1, 10).reshape(3, 3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

np.concatenate([arr1, arr2]).reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
mat1 = np.array([[1, 2, 3, 3], [3, 4, 5, 2], [7, 8, 9, 10]])

In [73]:
np.sum(mat1)

57

In [ ]:
np.sum(mat1, axis=0)  ### column별 총합

array([11, 14, 17, 15])

In [ ]:
np.sum(mat1, axis=1)  ### row별 총합

array([ 9, 14, 34])

In [ ]:
np.sort(mat1)

array([[ 1,  2,  3,  3],
       [ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])